import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/nav/Navbar";
import StoreProvider from "@/components/providers/StoreProvider";
import getThemeCookie from "@/utils/getThemeCookie.mjs";
import { verifyToken } from "@/utils/verifyToken.mjs";
import { makeStore } from "@/store/store";
import { setUserData } from "@/store/slices/authSlice";
import { setTheme } from "@/store/slices/themeSlice";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let storedTheme = await getThemeCookie();
  let userData = await verifyToken();
  const store = makeStore();
  store.dispatch(setUserData(userData));
  store.dispatch(setTheme(storedTheme));
  const initialReduxState = store.getState();

  return (
    <html lang="en">
      <StoreProvider initialReduxState={initialReduxState}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Navbar />
          {children}
        </body>
      </StoreProvider>
    </html>
  );
}
